# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Trabajos\8cuatrimestre\Inteligencia_Artificial\Corte_3\Actividad_3\View\home_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 345)
        MainWindow.setStyleSheet("background-color: rgb(39, 77, 116);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 30, 351, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Sitka Subheading\";\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.comboBox_listaUbicaciones = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_listaUbicaciones.setGeometry(QtCore.QRect(30, 150, 151, 31))
        self.comboBox_listaUbicaciones.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 48, 72);")
        self.comboBox_listaUbicaciones.setObjectName("comboBox_listaUbicaciones")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 51, 31))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 110, 121, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.spinBox_numHabitaciones = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numHabitaciones.setGeometry(QtCore.QRect(660, 150, 51, 21))
        self.spinBox_numHabitaciones.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 48, 72);")
        self.spinBox_numHabitaciones.setMinimum(1)
        self.spinBox_numHabitaciones.setObjectName("spinBox_numHabitaciones")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 110, 121, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_metrosCuadrados = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_metrosCuadrados.setGeometry(QtCore.QRect(480, 150, 62, 22))
        self.doubleSpinBox_metrosCuadrados.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 48, 72);")
        self.doubleSpinBox_metrosCuadrados.setMinimum(50.0)
        self.doubleSpinBox_metrosCuadrados.setMaximum(1000.0)
        self.doubleSpinBox_metrosCuadrados.setSingleStep(10.0)
        self.doubleSpinBox_metrosCuadrados.setProperty("value", 50.0)
        self.doubleSpinBox_metrosCuadrados.setObjectName("doubleSpinBox_metrosCuadrados")
        self.pushButton_consultarPrecio = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_consultarPrecio.setGeometry(QtCore.QRect(430, 230, 141, 28))
        self.pushButton_consultarPrecio.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_consultarPrecio.setObjectName("pushButton_consultarPrecio")
        self.label_precio = QtWidgets.QLabel(self.centralwidget)
        self.label_precio.setGeometry(QtCore.QRect(420, 290, 161, 21))
        self.label_precio.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 10pt \"Nirmala UI\";")
        self.label_precio.setText("")
        self.label_precio.setAlignment(QtCore.Qt.AlignCenter)
        self.label_precio.setObjectName("label_precio")
        self.pushButton_mostrarGrafica = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mostrarGrafica.setGeometry(QtCore.QRect(740, 280, 131, 28))
        self.pushButton_mostrarGrafica.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_mostrarGrafica.setObjectName("pushButton_mostrarGrafica")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 110, 81, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.spinBox_numBanios = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_numBanios.setGeometry(QtCore.QRect(810, 150, 51, 21))
        self.spinBox_numBanios.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 48, 72);")
        self.spinBox_numBanios.setMinimum(1)
        self.spinBox_numBanios.setObjectName("spinBox_numBanios")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 110, 111, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.comboBox_listaPropiedades = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_listaPropiedades.setGeometry(QtCore.QRect(250, 150, 151, 31))
        self.comboBox_listaPropiedades.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(24, 48, 72);")
        self.comboBox_listaPropiedades.setObjectName("comboBox_listaPropiedades")
        self.label_errorDepartamento = QtWidgets.QLabel(self.centralwidget)
        self.label_errorDepartamento.setGeometry(QtCore.QRect(70, 220, 281, 61))
        self.label_errorDepartamento.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_errorDepartamento.setAlignment(QtCore.Qt.AlignCenter)
        self.label_errorDepartamento.setWordWrap(True)
        self.label_errorDepartamento.setObjectName("label_errorDepartamento")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PREDICCIÓN DE BÚSQUEDA PARA HOGARES"))
        self.label_2.setText(_translate("MainWindow", "Ciudad"))
        self.label_3.setText(_translate("MainWindow", "No. de habitaciones"))
        self.label_4.setText(_translate("MainWindow", "Metros cuadrados"))
        self.pushButton_consultarPrecio.setText(_translate("MainWindow", "CONSULTAR PRECIO"))
        self.pushButton_mostrarGrafica.setText(_translate("MainWindow", "MOSTRAR GRÁFICA"))
        self.label_5.setText(_translate("MainWindow", "No. de baños"))
        self.label_6.setText(_translate("MainWindow", "Tipo de propiedad"))
        self.label_errorDepartamento.setText(_translate("MainWindow", "DEPARTAMENTOS NO DISPONIBLES EN LA CIUDAD SELECCIONADA"))
